# Generated by Django 3.2.9 on 2021-12-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_classification', models.CharField(max_length=1000, verbose_name='코스구분명')),
                ('course_name', models.CharField(max_length=1000, verbose_name='코스명')),
                ('departure', models.CharField(max_length=1000, verbose_name='출발점')),
                ('arrival', models.CharField(max_length=1000, verbose_name='도착점')),
                ('hours', models.CharField(max_length=1000, verbose_name='소요시간')),
                ('mins', models.CharField(max_length=1000, verbose_name='소요분')),
                ('introduce', models.CharField(max_length=1000, verbose_name='소개')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=1000, verbose_name='코스명')),
                ('departure', models.CharField(max_length=1000, verbose_name='출발점')),
                ('arrival', models.CharField(max_length=1000, verbose_name='도착점')),
                ('introduce', models.CharField(max_length=1000, verbose_name='소개')),
                ('courseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinfo')),
            ],
        ),
    ]
