# Generated by Django 3.2.9 on 2021-12-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='course_classification',
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='theme',
            field=models.TextField(default='-', max_length=1000, verbose_name='코스구분명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='arrival',
            field=models.TextField(max_length=1000, verbose_name='도착점'),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='course_name',
            field=models.TextField(max_length=1000, verbose_name='코스명'),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='departure',
            field=models.TextField(max_length=1000, verbose_name='출발점'),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='introduce',
            field=models.TextField(max_length=1000, verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='arrival',
            field=models.TextField(max_length=1000, verbose_name='도착점'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course_name',
            field=models.TextField(max_length=1000, verbose_name='코스명'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='departure',
            field=models.TextField(max_length=1000, verbose_name='출발점'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='hours',
            field=models.TextField(max_length=1000, verbose_name='소요시간'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='introduce',
            field=models.TextField(max_length=1000, verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='mins',
            field=models.TextField(max_length=1000, verbose_name='소요분'),
        ),
    ]
