# Generated by Django 3.2.9 on 2021-12-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211213_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseadd',
            name='arrival',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='course_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='departure',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='introduce',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='arrival',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='departure',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='hours',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='introduce',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='mins',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='theme',
            field=models.TextField(),
        ),
    ]
